FROM continuumio/miniconda3
LABEL maintainer="zhai@uchicago.edu"

RUN pip install --upgrade pip

COPY 		requirements_docker.txt /tmp/requirements_docker.txt
WORKDIR 	/tmp
RUN 		pip install -r requirements_docker.txt

RUN [ "python", "-c", "import nltk; nltk.download('punkt')" ]
RUN [ "python", "-c", "import nltk; nltk.download('wordnet')" ]
RUN [ "python", "-c", "import nltk; nltk.download('stopwords')" ]